### ISSUE TITLE
Theme generated advance

### ISSUE THREAD

**Issue by uhlhosting** [carolinan/fullsiteediting#31]
Hi,

Found this when generated an advance theme:

```
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.0.1
Active theme: Oxygen Base (version 1.0.0)
Current plugin:  (version )
PHP version 8.0.21



Error Details
=============
An error of type E_ERROR was caused in line 19 of the file /var/www/html/wp-content/themes/oxygen-base/patterns/footer-links.php. Error message: Uncaught Error: Call to undefined function oxygen_base_privacy() in /var/www/html/wp-content/themes/oxygen-base/patterns/footer-links.php:19
Stack trace:
#0 /var/www/html/wp-includes/block-patterns.php(326): include()
#1 /var/www/html/wp-includes/class-wp-hook.php(307): _register_theme_block_patterns('')
#2 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#4 /var/www/html/wp-settings.php(598): do_action('init')
#5 /var/www/html/wp-config.php(106): require_once('/var/www/html/w...')
#6 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
#7 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...')
#8 /var/www/html/wp-admin/themes.php(10): require_once('/var/www/html/w...')
#9 {main}
 thrown
```

Guess the oxygen_base_privacy function is not properly in use.

**Comment by carolinan** [comment]
Hi!
I have not been able to reproduce this. In inc/register-block-patterns.php, line 34,  do you have a function called oxygen_base_privacy() ?

**Comment by uhlhosting** [comment]
Yes, here is what I got generated.
[oxygen-base.zip](https://github.com/carolinan/fullsiteediting/files/9273964/oxygen-base.zip)

**Comment by carolinan** [comment]
I am still not able to reproduce this. I used the zip file on two different server setups.
Can you walk me through _all_ the steps to reproduce it?
Where do you see the error?

**Comment by carolinan** [comment]
I think that for now, I am just going to remove it in the next update. Because it is easy enough to add the privacy policy in a navigation block or just as a direct link in a paragraph.
